
Using device: cpu
Traceback (most recent call last):
  File "/home/adam/Documents/research_internship/ood_slam/slam_performance_model/scripts/train.py", line 115, in <module>
    train_model(config)
  File "/home/adam/Documents/research_internship/ood_slam/slam_performance_model/scripts/train.py", line 75, in train_model
    for data, labels in train_loader:
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/slam_performance_model/utils/dataloader.py", line 71, in __getitem__
    label = np.loadtxt(label_path, dtype=np.float32)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py", line 1380, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py", line 997, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/numpy/lib/_datasource.py", line 192, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/Documents/research_internship/ood_slam/env/lib/python3.12/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /media/adam/T9/ood_slam_data/datasets/pytorch_data/orb_slam/stereo/train/labels/regression/16_rpe_000212.txt not found.